version: "3"
services:
  database:
    image: postgres:14.5
    container_name: pg_14_5_metabase
    platform: linux/amd64
    restart: always
    ports:
      - 5432:5432
    environment:
      POSTGRES_PASSWORD: postgres
      PGDATA: /var/lib/postgresql/data
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./00-init.sql:/docker-entrypoint-initdb.d/00-init.sql
      - ./01-export.sql:/docker-entrypoint-initdb.d/01-export.sql
    networks:
      default:
        aliases:
          - postgres
  metabase:
    container_name: trantor_metabase_0_45_1
    platform: linux/amd64
    build:
      context: .
      dockerfile: Dockerfile
    image: trantor/metabase:v0.45.1
    restart: on-failure
    ports:
      - 3000:3000
    # volumes:
    #   - dataviz-data:/metabase-data
    environment:
      MB_DB_FILE: /app/metabase-data/metabase.db
      MB_DB_TYPE: postgres
      MB_DB_DBNAME: metabase
      MB_DB_PORT: 5432
      MB_DB_USER: postgres
      MB_DB_PASS: postgres
      MB_DB_HOST: postgres
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000"]
      interval: 10s
      timeout: 10s
      retries: 10
      start_period: 30s
    depends_on:
      - database
    networks:
      default:
        aliases:
          - metabase
volumes:
  db-data:
  # dataviz-data:
networks:
  default:
    name: metabase-network
